### PR TITLE
Add support for `custom_headers` parameter in webhook subscription

### PR DESCRIPTION
**Pull request by smaeda-ks**

### CODE REVIEW

**Review by stmcallister — APPROVED** [review]
Looks good! Thank you!! 👍 🎉

**Comment by smaeda-ks** [comment]
@stmcallister You're welcome! One thing to note is that some refactoring work might be needed due to the side effect of `omitempty` use across shared struct fields. For instance, because of the current model, I can't delete and "blank" the added custom headers via this client library and so the PD Terraform module (partial delete is possible, e.g., 2 -> 1 header).

If I just remove `omitempty` from the `CustomHeaders` field (or use pointers), the outgoing POST payload would include `"custom_headers": null`, which will get a 400 error from the upstream endpoint upon **CREATE** call, unfortunately. In other words, `"custom_headers": null` is only allowed for **UPDATE**.

FYI, the exact error message is below:

```

---[ REQUEST ]---------------------------------------
POST /webhook_subscriptions HTTP/1.1
Host: api.pagerduty.com
User-Agent: heimweh/go-pagerduty(terraform)
Content-Length: 317
Accept: application/vnd.pagerduty+json;version=2
Authorization: Token token=****
Content-Type: application/json
Accept-Encoding: gzip

{
 "webhook_subscription": {
  "type": "webhook_subscription",
  "active": true,
  "description": "via terraform",
  "delivery_method": {
   "type": "http_delivery_method",
   "url": "https://example.com/receive_a_pagerduty_webhook",
   "custom_headers": null
  },
  "events": [
   "incident.acknowledged"
  ],
  "filter": {
   "id": "PWNO3GH",
   "type": "service_reference"
  }
 }
}

---[ RESPONSE ]--------------------------------------
HTTP/2.0 400 Bad Request
Content-Length: 108
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers:
Cache-Control: max-age=0, private, must-revalidate
Content-Type: application/vnd.pagerduty+json; version=2; charset=UTF-8
Date: Mon, 07 Feb 2022 20:25:12 GMT
Server: nginx
X-Request-Id: ff1a028bc57c6fdadf2b5bbb602d91f1

{
 "errors": {
  "webhook_subscription": {
   "delivery_method": {
    "type": [
     "can't be blank"
    ],
    "url": [
     "can't be blank"
    ]
   }
  }
 }
}
```

\* as you can see, even though the actual problem is originated by the `custom_headers` parameter value, the error message is misleading and confusing. This might just be a bug on the PD side, I think.

The ideal behavior (also for the sake of better developer experience) is that the PD API allows and understands `null` and treats it as it if received an empty array `[]` regardless of CREATE/UPDATE, rather than returns an error in that way.
If this upstream change on the PD API side is unacceptable, we might need to introduce a separate struct for UPDATE call, and this might be the case across all endpoints, so I didn't include that work in this PR just yet.

Hope that makes sense to you.

| op | payload | response |
| --- | --- | --- |
| POST | `"custom_headers": null` | **400** |
| POST | `"custom_headers": []` | 200 |
| PUT | `"custom_headers": null` | 200 |
| PUT | `"custom_headers": []` | 200 |

**Comment by stmcallister** [comment]
Thanks for sharing this feedback @smaeda-ks! I've shared it with the engineering team in charge of the `webhook_subscriptions` API.

**Comment by smaeda-ks** [comment]
Thank you, @stmcallister! Hope that's an easy one to fix. Once it's fixed, we should be able to remove `omitempty` from there safely, in which I'm happy to help as long as I get noticed/notified :)

**Comment by ChezCrawford** [comment]
@smaeda-ks @stmcallister : This is some strange behavior 😉 . It may be a few days but we will get this taken care of.

**Comment by ChezCrawford** [comment]
> @smaeda-ks @stmcallister : This is some strange behavior 😉 . It may be a few days but we will get this taken care of.

`POST` w/ `"custom_headers": null` should now behave properly.

**Comment by smaeda-ks** [comment]
@ChezCrawford That's great news! Thanks for chasing this down! Much appreciated.

**Pull request merged**
