### PR TITLE
Add `ServicePayload` to remove nested `Service` attribute from `Service` struct

### LINKED ISSUE #57: `Service` struct should not contain a `Service` attribute
Since the very first commit, there is a `Service` attribute in the `Service` struct: 
```
// Service represents a service.
type Service struct {
	AcknowledgementTimeout int                        `json:"acknowledgement_timeout,omitempty"`
	Addons                 []*AddonReference          `json:"addons,omitempty"`
	AlertCreation          string                     `json:"alert_creation,omitempty"`
	AutoResolveTimeout     int                        `json:"auto_resolve_timeout,omitempty"`
	CreatedAt              string                     `json:"created_at,omitempty"`
	Description            string                     `json:"description,omitempty"`
	EscalationPolicy       *EscalationPolicyReference `json:"escalation_policy,omitempty"`
	HTMLURL                string                     `json:"html_url,omitempty"`
	ID                     string                     `json:"id,omitempty"`
	IncidentUrgencyRule    *IncidentUrgencyRule       `json:"incident_urgency_rule,omitempty"`
	Integrations           []*IntegrationReference    `json:"integrations,omitempty"`
	LastIncidentTimestamp  string                     `json:"last_incident_timestamp,omitempty"`
	Name                   string                     `json:"name,omitempty"`
	ScheduledActions       []*ScheduledAction         `json:"scheduled_actions,omitempty"`
	Self                   string                     `json:"self,omitempty"`
	Service                *Service                   `json:"service,omitempty"`
	Status                 string                     `json:"status,omitempty"`
	Summary                string                     `json:"summary,omitempty"`
	SupportHours           *SupportHours              `json:"support_hours,omitempty"`
	Teams                  []*TeamReference           `json:"teams,omitempty"`
	Type                   string                     `json:"type,omitempty"`
}
```
https://github.com/heimweh/go-pagerduty/commit/a458ce4770cdfc45f4fa0afe0706eb8f9b9d24aa#diff-3a590e889ca6befd01b803e4b0af6fb3041552eead1463e0dca0b087c343f692R78

This looks like a copy/paste error from other structs as there is no matching attribute in the API for the `https://api.pagerduty.com/services` endpoint: https://developer.pagerduty.com/api-reference/reference/REST/openapiv3.json/paths/~1services/post

FWIW, I noticed this while debugging weird issues with the behaviour of terraform provider when running acceptance tests:

```
2021/08/20 09:17:11 [INFO] Creating PagerDuty service tf-d60pe
2021/08/20 09:17:11 [DEBUG] PagerDuty - Preparing POST request to /services with body: {"acknowledgement_timeout":null,"alert_grouping":null,"auto_resolve_timeout":null,"service":{"acknowledgement_timeout":1800,"alert_creation":"create_alerts_and_incidents","alert_grouping":"time","alert_grouping_timeout":1800,"alert_grouping_parameters":{},"auto_resolve_timeout":1800,"description":"foo","escalation_policy":{"id":"PX530JT","type":"escalation_policy_reference"},"name":"tf-d60pe"}}
2021/08/20 09:17:11 [DEBUG] PagerDuty API Request Details:
---[ REQUEST ]---------------------------------------
POST /services HTTP/1.1
Host: api.pagerduty.com
User-Agent: heimweh/go-pagerduty(terraform)
Content-Length: 398
Accept: application/vnd.pagerduty+json;version=2
Authorization: Token token=******
Content-Type: application/json
Accept-Encoding: gzip

{
 "acknowledgement_timeout": null,
 "alert_grouping": null,
 "auto_resolve_timeout": null,
 "service": {
  "acknowledgement_timeout": 1800,
  "alert_creation": "create_alerts_and_incidents",
  "alert_grouping": "time",
  "alert_grouping_timeout": 1800,
  "alert_grouping_parameters": {},
  "auto_resolve_timeout": 1800,
  "description": "foo",
  "escalation_policy": {
   "id": "PX530JT",
   "type": "escalation_policy_reference"
  },
  "name": "tf-d60pe"
 }
}

-----------------------------------------------------
2021/08/20 09:17:11 [DEBUG] PagerDuty API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 201 Created
Content-Length: 976
Access-Control-Allow-Headers: Authorization, Content-Type, AuthorizationOauth, X-EARLY-ACCESS
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: 
Access-Control-Max-Age: 1728000
Cache-Control: max-age=0, private, must-revalidate
Content-Type: application/json
Date: Fri, 20 Aug 2021 07:17:11 GMT
Etag: W/"517f34e20ed8089259a734bb0137b371"
Feature-Policy: accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'
Referrer-Policy: strict-origin-when-cross-origin
Server: nginx
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Request-Id: 513fe44f47c4cc052001d152acb18a20
X-Xss-Protection: 1; mode=block

{
 "service": {
  "id": "P71DGB9",
  "name": "tf-d60pe",
  "description": "foo",
  "created_at": "2021-08-20T09:17:11+02:00",
  "updated_at": "2021-08-20T09:17:11+02:00",
  "status": "active",
  "teams": [],
  "alert_creation": "create_alerts_and_incidents",
  "addons": [],
  "scheduled_actions": [],
  "support_hours": null,
  "last_incident_timestamp": null,
  "escalation_policy": {
   "id": "PX530JT",
   "type": "escalation_policy_reference",
   "summary": "tf-lrua3",
   "self": "https://api.pagerduty.com/escalation_policies/PX530JT",
   "html_url": "https://dev-claranet.pagerduty.com/escalation_policies/PX530JT"
  },
  "incident_urgency_rule": {
   "type": "constant",
   "urgency": "high"
  },
  "acknowledgement_timeout": 1800,
  "auto_resolve_timeout": 1800,
  "alert_grouping": null,
  "alert_grouping_timeout": null,
  "alert_grouping_parameters": {
   "type": null,
   "config": null
  },
  "integrations": [],
  "response_play": null,
  "type": "service",
  "summary": "tf-d60pe",
  "self": "https://api.pagerduty.com/services/P71DGB9",
  "html_url": "https://dev-claranet.pagerduty.com/service-directory/P71DGB9"
 }
}
-----------------------------------------------------
```

As you can see, some fields like `alert_grouping` are passed twice, once at the root defined as `null` and once in the nested `service` attribute as `alert_grouping`, and the response only returns the one at the root.

### PR DESCRIPTION
**Pull request by pdecat**
This PR resolves https://github.com/heimweh/go-pagerduty/issues/57

### CODE REVIEW

**Comment by stmcallister** [comment]
Totally agree with this change. This is how we design resources today. Just one ask before approving. Will you also fix the `service_test.go`? I received the following error when I ran the tests. Thanks! 

```
==> Checking that code complies with gofmt requirements... ✔
==> Checking that code complies with go vet requirements...# github.com/heimweh/go-pagerduty/pagerduty
vet: pagerduty/service_test.go:41:27: v.Service undefined (type *Service has no field or method Service)
 ✔
==> Checking for misspelling errors... ✔
==> Checking that code complies with staticcheck requirements...pagerduty/service_test.go:41:27: v.Service undefined (type *Service has no field or method Service) (compile)
pagerduty/service_test.go:111:27: v.Service undefined (type *Service has no field or method Service) (compile)
make: *** [staticcheck] Error 1
```

**Comment by heimweh** [comment]
Nice job @pdecat! Really appreciate it! Been wanting to tackle this for some time now 😅
Unfortunately, we have more examples of this scattered across the codebase that I'd like to clean up as well. 
Let's use this and the new resources as an example going forward and try to align the existing resources the same way 👍

**Comment by pdecat** [comment]
Fixed the tests:

```
# make test
==> Checking that code complies with gofmt requirements... ✔
==> Checking that code complies with go vet requirements... ✔
==> Checking for misspelling errors... ✔
==> Checking that code complies with staticcheck requirements... ✔
==> Checking that code complies with golint requirements... ✔
==> Checking that code complies with unit tests...
ok      github.com/heimweh/go-pagerduty/pagerduty       0.048s  coverage: 62.3% of statements
```

**Comment by pdecat** [comment]
Submitted https://github.com/heimweh/go-pagerduty/pull/61 to enable Github Actions to run them automatically.

**Review by stmcallister — APPROVED** [review]
Awesome! Thank you!! 🎉

**Review by heimweh — APPROVED** [review]

**Pull request merged**
