### PR TITLE
feature: Support setting user's role on a team

### PR DESCRIPTION
**Pull request by mrwacky42**
I am hoping to extend the PagerDuty Terraform provider to allow me to set a member's role on the team. This is the first step.

### CODE REVIEW

**Comment by dtan4** [comment]
@heimweh This change will also help us since we manage PagerDuty Team members by Terraform. Could you take a look?

**Review by heimweh — CHANGES_REQUESTED** [review]
Hi @mrwacky42, 

thanks for this contribution! :pray:

I'd prefer to have the PagerDuty API validate and set various defaults to avoid this from becoming stale when new roles are added. Would you mind changing it to just pass the role as-is? 🙂

**Comment by mrwacky42** [comment]
Hi @heimweh,

It's been a while. I pushed a commit that I think is what you are asking for.

**Review by heimweh — APPROVED** [review]
Hey @mrwacky42,

very sorry for the delay on this one.

Thank you so much for this! This LGTM :ok_hand: :pray:

**Pull request merged**
