### PR TITLE
Add service integration email filters

### PR DESCRIPTION
**Pull request by tibibo**
Required for adding support for email filters and parsers configuration for email service integrations 
https://github.com/terraform-providers/terraform-provider-pagerduty/issues/88

### CODE REVIEW

**Comment by tibibo** [comment]
@heimweh could you review, please?

**Review by SpamapS — APPROVED** [review]
I'm nobody, but this seems correct to me, and would remove some clicking-hacks from our automation.

**Comment by stmcallister** [comment]
@tibibo thanks for submitting this! Unfortunately, this is an undocumented part of the PagerDuty API. I've been trying to hunt down the answer of whether there is a plan on documenting it. Once I have that I can make the decision of whether to merge this (and the subsequent feature in the Terraform provider) or not. I'll post back to this thread when I get an answer.

**Comment by jan-scorito** [comment]
I was looking into this as well, and stumbled upon this PR. Any updates on this? Or is there another way to set custom rules for e-mailmanagement through Terraform?

**Comment by tibibo** [comment]
@stmcallister as I see missing part have added in documentation —  https://developer.pagerduty.com/api-reference/reference/REST/openapiv3.json/paths/~1services~1%7Bid%7D~1integrations/post (Check tab "Email Integration With Filters"). Could you review this PR, please.

**Comment by jregovic** [comment]
Can this get merged?

**Review by stmcallister — APPROVED** [review]
This looks good! Sorry for the delay on reviewing!

**Pull request merged**
